name: Automate Pull Request Management

on:
  pull_request:
    types: [opened]

jobs:
  automate-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Assign default assignee, add labels and add to project
      uses: actions/github-script@v6
      with:
        script: |
          // Asignar PR
          await github.rest.issues.addAssignees({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            assignees: ['temPLAY333']
          });
          
          // Añadir etiqueta
          await github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['enhancement']
          });
          
          try {
            // Intentar añadir al proyecto (esto depende de la API de proyectos)
            const projects = await github.rest.projects.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            const project = projects.data.find(p => p.name === 'TP-4');
            
            if (project) {
              await github.rest.projects.createCard({
                project_id: project.id,
                content_id: context.payload.pull_request.id,
                content_type: 'PullRequest'
              });
            }
          } catch (error) {
            console.log('Error al añadir al proyecto: ' + error);
          }

    - name: Add default comment
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `⚠️ **Completa los siguientes campos para registrar este Pull Request correctamente.**\n\n- **Objetivo:** Describe el objetivo del Pull Request.\n- **Detalles:** Explica brevemente los pasos o componentes involucrados.\n- **Checklist:**\n  - [ ] La funcionalidad está implementada correctamente\n  - [ ] Se probó la funcionalidad en \`Main\` o test correspondiente\n  - [ ] Se creó una rama específica para este Pull Request\n  - [ ] Este Pull Request menciona el Issue relacionado.`
          });